### ISSUE TITLE
Run failed  ``TTS Text generation failed: No module named 'utils.audio.audio_hash'

### ISSUE THREAD

**Issue by windy-bleue** [diodiogod/TTS-Audio-Suite#12]
I can run your chatterbox srt successfully.   When i want to upgrade to tts-audio-suite, i can install it sucessfully, all seem ok and correct, both 'pip install -r requirements.txt' and 'python install.py' . 
When i try your example , here is un error "Run failed  TTS Text generation failed: No module named 'utils.audio.audio_hash" , and in the process of the comfyui start, there are two errors: 
❌ RVC Engine failed: No module named 'engines.adapters.rvc_adapter'
❌ Vocal/Noise Removal failed: No module named 'karafan'

Here is the error message
got prompt
⚙️ ChatterBox Engine: Configured for English on auto
   Settings: exaggeration=0.5, temperature=0.8, cfg_weight=0.5
   Crash protection: hmm ,, {seg} hmm ,,
⚠️ TTS Text: No voice reference provided - this may cause issues with some engines
🎤 Generating Chatterbox for 'narrator' (lang: en)
❌ TTS Text generation failed: No module named 'utils.audio.audio_hash'
Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\unified/tts_text_node.py", line 401, in generate_speech
    result = engine_instance.generate_speech(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 932, in generate_speech
    return self.process_with_error_handling(_process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 588, in _process
    stable_audio_component = self._generate_stable_audio_component(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 400, in _generate_stable_audio_component
    from utils.audio.audio_hash import generate_stable_audio_component
ModuleNotFoundError: No module named 'utils.audio.audio_hash'

**Comment by diodiogod** [comment]
🔧 **Potential fix in v4.6.2!**

I've identified and fixed the module discovery issue you're experiencing. This appears to be caused by different ComfyUI installation setups where the Python path isn't consistently maintained for lazy imports.

**What was fixed:**
- Added path verification before lazy imports in ChatterBox TTS and SRT nodes
- Fixed the specific `No module named 'utils.audio.audio_hash'` error
- Made imports more robust across different Python environments and ComfyUI setups

**Please test v4.6.2:**
1. Update to the latest version
2. Try running the ChatterBox TTS Text node that was failing before
3. Let me know if you still get any import errors

The fix preserves all existing functionality while making the import system more reliable. If this resolves your issue, great! If you're still having problems, please share the new error messages and I'll investigate further.

**Note:** The RVC and Karafan warnings you mentioned might be related to missing optional dependencies rather than path issues. If those persist after this fix, we can address them separately.

**Comment by diodiogod** [comment]
🔧 **Enhanced fix in v4.6.3 for conda environments!**

I believe the issue is specifically related to **conda environment isolation**. I've implemented a more robust solution that should work with conda's aggressive import caching and path management.

**What's new in v4.6.3:**
- Enhanced import error handling specifically for conda environments
- Automatic cache invalidation (`importlib.invalidate_caches()`) when imports fail
- Zero performance impact on working installations
- Better fallback logic for isolated Python environments

**Please test v4.6.3:**
1. Update to the latest version: `git pull`
2. Restart your conda environment completely
3. Try running the ChatterBox TTS Text node again

**If it still doesn't work, can you help with a quick diagnostic?**
Run this in your conda environment's Python:
```python
import sys
import os
print("Python executable:", sys.executable)
print("Current working directory:", os.getcwd())

# Check if the file exists
file_path = "path/to/your/ComfyUI/custom_nodes/TTS-Audio-Suite/utils/audio/audio_hash.py"
print("File exists:", os.path.exists(file_path))

# Try the import
try:
    import importlib
    sys.path.insert(0, "path/to/your/ComfyUI/custom_nodes/TTS-Audio-Suite")
    importlib.invalidate_caches()
    from utils.audio.audio_hash import generate_stable_audio_component
    print("✅ Manual import successful!")
except Exception as e:
    print("❌ Manual import failed:", str(e))
```

This version specifically targets conda's unique behavior. Fingers crossed this resolves it! 🤞

**Comment by windy-bleue** [comment]
Hi, the problems are still here, and i run your code,  the output it: 
...
✅ Manual import successful!
>>>

**Comment by diodiogod** [comment]
Thanks for testing the diagnostic script! 

That's very interesting - the manual import **works successfully** ✅, but you're still getting problems with the actual node. This tells me there might be a timing or context difference between manual import and the node execution.

**Can you help with one more thing?**

Since the problems persist, could you **post the complete console log again** when you try to run the ChatterBox TTS Text node? I want to see:

1. **Is the exact same error still appearing?** (`No module named 'utils.audio.audio_hash'`)
2. **Are there any new/different error messages?**
3. **What does the full error trace look like now?**

**Also, please clarify:**
- Are you still getting the original `utils.audio.audio_hash` import error from your first post?
- Or are you now getting different errors?
- Is the Voice Changer TypeError a separate issue or related?

The fact that the manual import succeeds but the node fails suggests the issue might be **context-specific** - happening only when ComfyUI loads and executes the node. A full error log will help me understand what's happening in that specific context.

Thanks for your patience! 🙏

**Comment by windy-bleue** [comment]
The follow appears in the comfyui start process:
❌ RVC Engine failed: No module named 'engines.adapters.rvc_adapter'
❌ Vocal/Noise Removal failed: No module named 'karafan'
======================================================================
🚀 TTS Audio Suite v4.6.3
Universal multi-engine TTS extension for ComfyUI
⚠️ No local ChatterBox models found - will download from Hugging Face
💡 Tip: First generation will download models (~1GB)
   Models will be saved locally for future use
✅ TTS Audio Suite v4.6.3 loaded with 18 nodes:
   • ⚙️ ChatterBox TTS Engine
   • ⚙️ F5 TTS Engine
   • ⚙️ Higgs Audio 2 Engine
   • ⚙️ VibeVoice Engine
   • 🌊 Audio Wave Analyzer
   • 🎙️ Voice Capture
   • 🎤 TTS Text
   • 🎭 Character Voices
   • 🎭 Load RVC Character Model
   • 👄 F5-TTS Speech Editor
   • 📺 TTS SRT
   • 🔄 Voice Changer
   • 🔧 Audio Analyzer Options
   • 🔧 F5-TTS Edit Options
   • 🔧 RVC Pitch Extraction Options
   • 🔧 Viseme Mouth Shape Options
   • 🗣️ Silent Speech Analyzer
   • 🥪 Merge Audio
======================================================================

The follow is the output when i run the chatterbox integration
[ComfyUI-Manager] All startup tasks have been completed.
got prompt
⚙️ ChatterBox Engine: Configured for English on auto
   Settings: exaggeration=0.5, temperature=0.8, cfg_weight=0.5
   Crash protection: hmm ,, {seg} hmm ,,
🔄 Voice Changer: Starting chatterbox voice conversion
🔄 Voice Changer: Using direct audio input for source_audio
🔄 Voice Changer: Using direct audio input for narrator_target
🔄 Voice Changer: Using English language model for conversion
❌ Voice conversion failed: Node processing failed: TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given
Traceback:
Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 154, in _process
    self.load_vc_model(device, language=language)
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 388, in load_vc_model
    self.vc_model = self.model_manager.load_vc_model(device, force_reload, language)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given

Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 154, in _process
    self.load_vc_model(device, language=language)
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 388, in load_vc_model
    self.vc_model = self.model_manager.load_vc_model(device, force_reload, language)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\unified/voice_changer_node.py", line 436, in convert_voice
    result = engine_instance.convert_voice(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 234, in convert_voice
    return self.process_with_error_handling(_process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 285, in process_with_error_handling
    raise RuntimeError(
RuntimeError: Node processing failed: TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given
Traceback:
Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 154, in _process
    self.load_vc_model(device, language=language)
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 388, in load_vc_model
    self.vc_model = self.model_manager.load_vc_model(device, force_reload, language)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given

⚠️ TTS Text: No voice reference provided - this may cause issues with some engines
🐛 TTS_TEXT: Final fallback - opt_narrator=False, narrator_voice='none'
🎤 Generating Chatterbox for 'narrator' (lang: en)
❌ TTS Text generation failed: No module named 'utils.audio.audio_hash'
Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 402, in _generate_stable_audio_component
    from utils.audio.audio_hash import generate_stable_audio_component
ModuleNotFoundError: No module named 'utils.audio.audio_hash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\unified/tts_text_node.py", line 522, in generate_speech
    result = engine_instance.generate_speech(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 942, in generate_speech
    return self.process_with_error_handling(_process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 598, in _process
    stable_audio_component = self._generate_stable_audio_component(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 410, in _generate_stable_audio_component
    from utils.audio.audio_hash import generate_stable_audio_component
ModuleNotFoundError: No module named 'utils.audio.audio_hash'
Prompt executed in 0.22 seconds

**Comment by windy-bleue** [comment]
Hi,does it something wrong with my comfyui envoirement, the problems are still there:
[rgthree-comfy] Loaded 48 exciting nodes. 🎉

❌ RVC Engine failed: No module named 'engines.adapters.rvc_adapter'
❌ Vocal/Noise Removal failed: No module named 'karafan'
======================================================================
🚀 TTS Audio Suite v4.6.4
Universal multi-engine TTS extension for ComfyUI
⚠️ No local ChatterBox models found - will download from Hugging Face
💡 Tip: First generation will download models (~1GB)
   Models will be saved locally for future use
✅ TTS Audio Suite v4.6.4 loaded with 18 nodes:
   • ⚙️ ChatterBox TTS Engine
   • ⚙️ F5 TTS Engine
   • ⚙️ Higgs Audio 2 Engine
   • ⚙️ VibeVoice Engine
   • 🌊 Audio Wave Analyzer
   • 🎙️ Voice Capture
   • 🎤 TTS Text
   • 🎭 Character Voices
   • 🎭 Load RVC Character Model
   • 👄 F5-TTS Speech Editor
   • 📺 TTS SRT
   • 🔄 Voice Changer
   • 🔧 Audio Analyzer Options
   • 🔧 F5-TTS Edit Options
   • 🔧 RVC Pitch Extraction Options
   • 🔧 Viseme Mouth Shape Options
   • 🗣️ Silent Speech Analyzer
   • 🥪 Merge Audio
======================================================================

Here is the output of the Chatterbox integration:

[ComfyUI-Manager] All startup tasks have been completed.
got prompt
⚙️ ChatterBox Engine: Configured for English on auto
   Settings: exaggeration=0.5, temperature=0.8, cfg_weight=0.5
   Crash protection: hmm ,, {seg} hmm ,,
⚠️ TTS Text: No voice reference provided - this may cause issues with some engines
🐛 TTS_TEXT: Final fallback - opt_narrator=False, narrator_voice='none'
🎤 Generating Chatterbox for 'narrator' (lang: en)
❌ TTS Text generation failed: No module named 'utils.audio.audio_hash'
Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 402, in _generate_stable_audio_component
    from utils.audio.audio_hash import generate_stable_audio_component
ModuleNotFoundError: No module named 'utils.audio.audio_hash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\unified/tts_text_node.py", line 522, in generate_speech
    result = engine_instance.generate_speech(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 942, in generate_speech
    return self.process_with_error_handling(_process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 598, in _process
    stable_audio_component = self._generate_stable_audio_component(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 410, in _generate_stable_audio_component
    from utils.audio.audio_hash import generate_stable_audio_component
ModuleNotFoundError: No module named 'utils.audio.audio_hash'
🔄 Voice Changer: Starting chatterbox voice conversion
🔄 Voice Changer: Using direct audio input for source_audio
🔄 Voice Changer: Using direct audio input for narrator_target
🔄 Voice Changer: Using English language model for conversion
❌ Voice conversion failed: Node processing failed: TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given
Traceback:
Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 154, in _process
    self.load_vc_model(device, language=language)
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 388, in load_vc_model
    self.vc_model = self.model_manager.load_vc_model(device, force_reload, language)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given

Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 154, in _process
    self.load_vc_model(device, language=language)
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 388, in load_vc_model
    self.vc_model = self.model_manager.load_vc_model(device, force_reload, language)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\unified/voice_changer_node.py", line 436, in convert_voice
    result = engine_instance.convert_voice(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 234, in convert_voice
    return self.process_with_error_handling(_process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 285, in process_with_error_handling
    raise RuntimeError(
RuntimeError: Node processing failed: TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given
Traceback:
Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 154, in _process
    self.load_vc_model(device, language=language)
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 388, in load_vc_model
    self.vc_model = self.model_manager.load_vc_model(device, force_reload, language)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given

Prompt executed in 0.28 seconds

**Comment by diodiogod** [comment]
🔧 **New comprehensive fix in v4.6.8**

I've implemented a completely different approach - a robust import system that should handle module discovery issues across all environments (conda, Windows, venv, etc.).

**What changed:**
- New multi-strategy import system that tries different approaches
- Smart project root detection that doesn't rely on fragile path calculations
- Handles conda cache issues, Windows path problems, and partial module loading

**Please test v4.6.8:**
1. `git pull`
2. Restart your environment
3. Try ChatterBox TTS Text node

**@RuneGjerde** - This should also fix your `utils.models.comfyui_model_wrapper` issue since it addresses the broader module discovery problem.

I'm cautiously optimistic this will work, but let's see what happens. If it still fails, we'll know it's an even deeper environment issue and can explore other solutions.

**Comment by windy-bleue** [comment]
> 🔧 **New comprehensive fix in v4.6.8**


[rgthree-comfy] Loaded 48 exciting nodes. 🎉

❌ RVC Engine failed: No module named 'engines.adapters.rvc_adapter'
❌ Vocal/Noise Removal failed: No module named 'karafan'
======================================================================
🚀 TTS Audio Suite v4.6.8
Universal multi-engine TTS extension for ComfyUI
⚠️ No local ChatterBox models found - will download from Hugging Face
💡 Tip: First generation will download models (~1GB)
   Models will be saved locally for future use
✅ TTS Audio Suite v4.6.8 loaded with 18 nodes:
   • ⚙️ ChatterBox TTS Engine
   • ⚙️ F5 TTS Engine
   • ⚙️ Higgs Audio 2 Engine
   • ⚙️ VibeVoice Engine
   • 🌊 Audio Wave Analyzer
   • 🎙️ Voice Capture
   • 🎤 TTS Text
   • 🎭 Character Voices
   • 🎭 Load RVC Character Model
   • 👄 F5-TTS Speech Editor
   • 📺 TTS SRT
   • 🔄 Voice Changer
   • 🔧 Audio Analyzer Options
   • 🔧 F5-TTS Edit Options
   • 🔧 RVC Pitch Extraction Options
   • 🔧 Viseme Mouth Shape Options
   • 🗣️ Silent Speech Analyzer
   • 🥪 Merge Audio
======================================================================


To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 10/95
FETCH ComfyRegistry Data: 15/95
got prompt
WARNING: [Errno 2] No such file or directory: 'C:\\Users\\yao\\ComfyUI\\input\\Tony.mp3'
⚙️ ChatterBox Engine: Configured for English on auto
   Settings: exaggeration=0.5, temperature=0.8, cfg_weight=0.5
   Crash protection: hmm ,, {seg} hmm ,,
⚠️ TTS Text: No voice reference provided - this may cause issues with some engines
🐛 TTS_TEXT: Final fallback - opt_narrator=False, narrator_voice='none'
🎤 Generating Chatterbox for 'narrator' (lang: en)
❌ TTS Text generation failed: No module named 'utils.robust_import'
Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\unified/tts_text_node.py", line 522, in generate_speech
    result = engine_instance.generate_speech(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 935, in generate_speech
    return self.process_with_error_handling(_process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 591, in _process
    stable_audio_component = self._generate_stable_audio_component(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_tts_node.py", line 401, in _generate_stable_audio_component
    from utils.robust_import import robust_from_import
ModuleNotFoundError: No module named 'utils.robust_import'
🔄 Voice Changer: Starting chatterbox voice conversion
🔄 Voice Changer: Using direct audio input for source_audio
🔄 Voice Changer: Using direct audio input for narrator_target
🔄 Voice Changer: Using English language model for conversion
❌ Voice conversion failed: Node processing failed: TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given
Traceback:
Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 154, in _process    self.load_vc_model(device, language=language)
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 388, in load_vc_model
    self.vc_model = self.model_manager.load_vc_model(device, force_reload, language)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given

Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 154, in _process    self.load_vc_model(device, language=language)
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 388, in load_vc_model
    self.vc_model = self.model_manager.load_vc_model(device, force_reload, language)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\unified/voice_changer_node.py", line 436, in convert_voice
    result = engine_instance.convert_voice(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 234, in convert_voice
    return self.process_with_error_handling(_process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 285, in process_with_error_handling
    raise RuntimeError(
RuntimeError: Node processing failed: TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given
Traceback:
Traceback (most recent call last):
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 269, in process_with_error_handling
    return process_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\chatterbox\chatterbox_vc_node.py", line 154, in _process    self.load_vc_model(device, language=language)
  File "C:\Users\yao\ComfyUI\custom_nodes\TTS-Audio-Suite\nodes\base\base_node.py", line 388, in load_vc_model
    self.vc_model = self.model_manager.load_vc_model(device, force_reload, language)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelManager.load_vc_model() takes from 1 to 3 positional arguments but 4 were given

Prompt executed in 0.32 seconds

**Comment by RuneGjerde** [comment]
**Start up status messages (in case it has any interest or is of any help) (on booting up ComfyUI) :** 


Multiple distributions found for package optimum. Picked distribution: optimum
✅ ChatterboxTTS loaded from bundled package
✅ ChatterboxVC loaded from bundled package
TensorFlow version 2.17.1 available.
JAX version 0.7.1 available.
✅ F5-TTS loaded from system package
🎭 Character voices: Found 9 characters, 10 aliases
✅ SRT modules loaded from system package
======================================================================
🚀 ChatterBox Voice Extension v3.4.4
Using model source: huggingface
⚠️ No local models found - will download from Hugging Face
💡 Tip: First generation will download models (~1GB)
   Models will be saved locally for future use
======================================================================
🚀 ChatterBox Voice Extension v3.4.4 loaded with 10 nodes:
   • 🌊 Audio Wave Analyzer
   • 🎙️ ChatterBox Voice Capture (diogod)
   • 🎤 ChatterBox Voice TTS (diogod)
   • 🎤 F5-TTS Voice Generation
   • 👄 F5-TTS Speech Editor
   • 📺 ChatterBox SRT Voice TTS
   • 📺 F5-TTS SRT Voice Generation
   • 🔄 ChatterBox Voice Conversion (diogod)
   • 🔧 Audio Wave Analyzer Options
   • 🔧 F5-TTS Edit Options
======================================================================

-- - - - - - 

**Error message when running default workflow : **

 _(with audio clip connected)_ 
got prompt
⚙️ ChatterBox Engine: Configured for English on auto
   Settings: exaggeration=0.5, temperature=0.8, cfg_weight=0.5
   Crash protection: hmm ,, {seg} hmm ,,
🎤 TTS Text: Using direct audio input (narrator)
⚠️ TTS Text: Direct audio input has no reference text - F5-TTS engines will fail
🎤 Generating Chatterbox for 'narrator' (lang: en)
❌ TTS Text generation failed: No module named 'utils.robust_import'
-- - 

 _(with no audio clip connected - just using the TTT text node without external inputs)_ 

got prompt
🐛 TTS_TEXT: Trying narrator_voice dropdown: voices_examples/David_Attenborough CC3.wav
🐛 TTS_TEXT: Dropdown - audio_path=E:\AI\ComfyUI\custom_nodes\chatterbox_srt_voice\voices_examples\David_Attenborough CC3.wav, exists=True
🎤 TTS Text: Using voice reference from folder (David_Attenborough CC3)
🐛 TTS_TEXT: Dropdown loaded - character_name='David_Attenborough CC3', waveform_shape=torch.Size([1, 226436])
🎤 Generating Chatterbox for 'David_Attenborough CC3' (lang: en)
❌ Failed to create engine node instance: No module named 'utils.models.comfyui_model_wrapper'
❌ TTS Text generation failed: Failed to create engine node instance

**Comment by RuneGjerde** [comment]
And a newbie to this new TTS Audio Suite, so in case i was doing something wrong above, i tried adding reference audio clip:
(just in case this helps to narrow down where it goes wrong) 

got prompt
💬 Narrator Voice: Clint_Eastwood CC3 (enhanced2) ready for F5-TTS, ChatterBox, and future engines (text from voices_examples/Clint_Eastwood CC3 (enhanced2).wav)
🎤 TTS Text: Using voice reference from Character Voices node (Clint_Eastwood CC3 (enhanced2))
🐛 TTS_TEXT: Character Voices - character_name='Clint_Eastwood CC3 (enhanced2)', has_audio=True
🐛 TTS_TEXT: Audio keys: ['waveform', 'sample_rate']
🎤 Generating Chatterbox for 'Clint_Eastwood CC3 (enhanced2)' (lang: en)
❌ Failed to create engine node instance: No module named 'utils.models.comfyui_model_wrapper'
❌ TTS Text generation failed: Failed to create engine node instance

**Comment by diodiogod** [comment]
@RuneGjerde you need to delete the old project custom_node 'ChatterBox SRT Voice' and install this one. Your console log show you have v3.4.4, which is the old project. We are now at v4.6.8 and the node is called now TTS Audio Suite. Install it through the comfyui manager so it uses the installation script automatically.

**Comment by diodiogod** [comment]
> > [@RuneGjerde](https://github.com/RuneGjerde) you need to delete the old project custom_node 'ChatterBox SRT Voice' and install this one. Your console log show you have v3.4.4, which is the old project. We are now at v4.6.8 and the node is called now TTS Audio Suite. Install it through the comfyui manager so it uses the installation script automatically.
> 
> Yes thats what i been using prior to now trying out TTS-Audio-Suite. I'll remove Chatterbox SRT Voice, and start over ;-)
```
Yes, do that. Then post your comfyui console init message again. 
You can use the three ``` on the top and on the bottom of your message code so it doesn't get weird formatting, like this
```

**Comment by diodiogod** [comment]
The auto-download system is working correctly. Your issue appears to be corrupted or partial model files from previous installations.

**Please try this:**

1. **Delete ALL ChatterBox model folders** - Search for and delete these directories if they exist:
   - `C:\Users\yao\ComfyUI\models\TTS\chatterbox` (new location)
   - `C:\Users\yao\ComfyUI\models\chatterbox` (legacy location)
   - Any other `chatterbox` folders you find in your models directory

2. **Restart ComfyUI** completely

3. **Try the Voice Changer again** - it should auto-download fresh models (~1GB):
   ```
   📦 Loading ChatterBox VC model for English from ResembleAI/chatterbox
   📥 Downloading Chatterbox VC model to local directory: s3gen.pt
   📥 Downloading s3gen.pt: 100.0%
   ```

The system found partial/corrupted local files and tried to use them instead of downloading fresh ones.

Let me know if this fixes the Voice Changer issue.

**Comment by windy-bleue** [comment]
> Can I close this [@windy-bleue](https://github.com/windy-bleue) [@RuneGjerde](https://github.com/RuneGjerde) ? Are you guys having any more errors?

Yes , please, thanks! I am looking forward to the completion of this tts-audio-suite.
