### ISSUE TITLE
[Bug] TTS Text generation failed: Failed to load Step Audio EditX model: Input cfg is not an OmegaConf config object (dict)

### ISSUE THREAD

**Issue by jason-mightynice** [diodiogod/TTS-Audio-Suite#196]
When running the Step Audio EditX Integration example workflow, the TTS Text node gives an error

Traceback (most recent call last):
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\unified/tts_text_node.py", line 739, in generate_speech
    tts_processor = StepAudioEditXProcessor(wrapper_instance, config)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx\step_audio_editx_processor.py", line 58, in __init__
    self.adapter.load_base_model(model_path, device, torch_dtype, quantization)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\adapters\step_audio_editx_adapter.py", line 122, in load_base_model
    self.engine = unified_model_interface.load_model(config)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 156, in load_model
    wrapper = tts_model_manager.load_model(
        model_factory_func=factory_func,
    ...<5 lines>...
        config=config  # Pass entire config to factory
    )
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\utils\models\comfyui_model_wrapper\model_manager.py", line 253, in load_model
    model = model_factory_func(config)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 897, in step_audio_editx_factory
    raise RuntimeError(f"Failed to load Step Audio EditX model: {e}")
RuntimeError: Failed to load Step Audio EditX model: Input cfg is not an OmegaConf config object (dict)


🚀 TTS Audio Suite v4.15.3
Universal multi-engine TTS extension for ComfyUI
🐍 Python 3.13.6 detected
✅ TTS Audio Suite v4.15.3 loaded with 29 nodes:
   • ⚙️ ChatterBox Official 23-Lang Engine
   • ⚙️ ChatterBox TTS Engine
   • ⚙️ F5 TTS Engine
   • ⚙️ Higgs Audio 2 Engine
   • ⚙️ IndexTTS-2 Engine
   • ⚙️ RVC Engine
   • ⚙️ Step Audio EditX Engine
   • ⚙️ VibeVoice Engine
   • 🌈 IndexTTS-2 Emotion Vectors
   • 🌈 IndexTTS-2 Text Emotion
   • 🌊 Audio Wave Analyzer
   • 🎙️ Voice Capture
   • 🎤 TTS Text
   • 🎨 Step Audio EditX - Audio Editor
   • 🎭 Character Voices
   • 🎭 Load RVC Character Model
   • 🏷️ Multiline TTS Tag Editor
   • 👄 F5-TTS Speech Editor
   • 📝 Phoneme Text Normalizer
   • 📺 TTS SRT
   • 🔄 Voice Changer
   • 🔧 Audio Analyzer Options
   • 🔧 F5-TTS Edit Options
   • 🔧 RVC Pitch Extraction Options
   • 🔧 Viseme Mouth Shape Options
   • 🗣️ Silent Speech Analyzer
   • 🤐 Noise or Vocal Removal
   • 🤐 Voice Fixer
   • 🥪 Merge Audio
======================================================================
[VibeVoice] SageAttention available for acceleration
[VibeVoice] Using embedded VibeVoice (MIT licensed)
[VibeVoice] VibeVoice nodes registered successfully
[TTS Audio Suite] 🎭 Character voices: Found 26 characters, 10 aliases (cached)
[TTS Audio Suite] 🔄 Updating character discovery in background...

**System information**
 - OS: Windows 11
 - ComfyUI type: portable
 - Python version: 3.13.6

**Additional context**
https://github.com/Saganaki22/ComfyUI-Step_Audio_EditX_TTS works  in the same comfyui environment.

the TTS models folder is a comfyui extra search path. Main comfyui folder is D drive.

Adding extra search path TTS E:\comfyui_external\models\TTS

**Comment by diodiogod** [comment]
I've investigated this issue and added better validation and error handling in v4.15.4.

## Analysis

The error suggests your CosyVoice model files may be corrupted or incomplete. The new version adds comprehensive file validation that will provide clearer error messages if files are missing or invalid.

## What Changed

1. **Better validation**: Checks that all CosyVoice files exist before attempting to load
2. **Improved compatibility**: Added `overrides={}` parameter to `load_hyperpyyaml()` for better version compatibility
3. **Clearer error messages**: If validation fails, you'll get specific instructions on what to delete and re-download

## Please Try This

1. **Update to v4.15.4**: Pull the latest version from the repository
2. **Delete the CosyVoice folder**:
   ```powershell
   Remove-Item -Recurse -Force "E:\comfyui_external\models\TTS\step_audio_editx\Step-Audio-EditX\CosyVoice-300M-25Hz"
   ```
3. **Re-run your workflow**: This will trigger automatic re-download of the CosyVoice model
4. **Report back**: Let me know if the issue is resolved or if you get a different error message

The new validation should either fix the issue or provide much better diagnostics about what's wrong with your model files.

**Comment by diodiogod** [comment]
I'll check your workaround. But about the transformers thing, I fixed it in my project. It was a misconfiguration of the model (not a transformers problem, not my implementation problem). I patched the model, and it should now work with any transformers version.

**Comment by jason-mightynice** [comment]
Thank you for your help!

I did redownload the models, but it was the same issue. Yes, comfyui-step-audio-editx-tts is causing some conflict. If I remove it, I do not get the original error, but I have another error (see below). This might be my environment. torch is 2.9.1+cu128 (windows with a 5090)

Also, as someone mentioned, transformers==4.53.3 is required, but would be great if it could work with a newer version!

LOG WITH comfyui-step-audio-editx-tts installed.

```
⚙️ Step Audio EditX: Configured on cuda
   Model: local:Step-Audio-EditX
   Precision: bfloat16
   Generation: temp=0.7, do_sample=True, max_tokens=8192
🎤 TTS Text: Using voice reference from folder (female_01)
🎤 Generating Step_Audio_Editx for 'female_01' (lang: en)
📁 Using local Step Audio EditX model: E:\comfyui_external\models\TTS\step_audio_editx\Step-Audio-EditX
download models from model hub: ms
Using model path: E:\comfyui_external\models\TTS\step_audio_editx\FunASR-Paraformer
❌ TTS Text generation failed: Failed to load Step Audio EditX model: Input cfg is not an OmegaConf config object (dict)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 908, in step_audio_editx_factory
    tokenizer = StepAudioTokenizer(
        encoder_path=model_path,
        model_source=ModelSource.LOCAL  # Always use local for now
    )
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\step_audio_editx\step_audio_editx_impl\tokenizer.py", line 61, in __init__
    self.funasr_model = AutoModel(
                        ~~~~~~~~~^
        model=local_funasr_path,
        ^^^^^^^^^^^^^^^^^^^^^^^^
        device="cuda:0" if torch.cuda.is_available() else "cpu",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        disable_log=True  # Suppress verbose registration tables
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-step-audio-editx-tts\step_audio_impl\funasr_detach\auto\auto_model.py", line 108, in __init__
    model, kwargs = self.build_model(**kwargs)
                    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-step-audio-editx-tts\step_audio_impl\funasr_detach\auto\auto_model.py", line 173, in build_model
    kwargs = download_model(**kwargs)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-step-audio-editx-tts\step_audio_impl\funasr_detach\download\download_from_hub.py", line 89, in download_model
    return OmegaConf.to_container(kwargs, resolve=True)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\python_embeded\Lib\site-packages\omegaconf\omegaconf.py", line 569, in to_container
    raise ValueError(
        f"Input cfg is not an OmegaConf config object ({type_str(type(cfg))})"
    )
ValueError: Input cfg is not an OmegaConf config object (dict)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\unified/tts_text_node.py", line 739, in generate_speech
    tts_processor = StepAudioEditXProcessor(wrapper_instance, config)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx\step_audio_editx_processor.py", line 58, in __init__
    self.adapter.load_base_model(model_path, device, torch_dtype, quantization)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\adapters\step_audio_editx_adapter.py", line 122, in load_base_model
    self.engine = unified_model_interface.load_model(config)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 156, in load_model
    wrapper = tts_model_manager.load_model(
        model_factory_func=factory_func,
    ...<5 lines>...
        config=config  # Pass entire config to factory
    )
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\utils\models\comfyui_model_wrapper\model_manager.py", line 253, in load_model
    model = model_factory_func(config)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\utils\models\unified_model_interface.py", line 931, in step_audio_editx_factory
    raise RuntimeError(f"Failed to load Step Audio EditX model: {e}")
RuntimeError: Failed to load Step Audio EditX model: Input cfg is not an OmegaConf config object (dict)
```


LOG WITHOUT comfyui-step-audio-editx-tts installed

```
Traceback (most recent call last):
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\unified/tts_text_node.py", line 864, in generate_speech
    audio_segments = tts_processor.process_text(
        text=text,
    ...<3 lines>...
        max_chars_per_chunk=max_chars_per_chunk if max_chars_per_chunk > 0 else 400
    )
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx\step_audio_editx_processor.py", line 126, in process_text
    return self._process_character_switching(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        segment_objects, voice_mapping, params,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        enable_chunking, max_chars_per_chunk
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx\step_audio_editx_processor.py", line 188, in _process_character_switching
    self._process_character_block(segment.character, segment.text.strip(), voice_mapping,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                segment_params, enable_chunking, max_chars, audio_segments)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx\step_audio_editx_processor.py", line 245, in _process_character_block
    self._process_single_text_segment(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        character, content, voice_mapping, params, audio_segments
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx\step_audio_editx_processor.py", line 398, in _process_single_text_segment
    audio_tensor = self.adapter._generate_direct(clean_text, voice_ref, params, character)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\adapters\step_audio_editx_adapter.py", line 314, in _generate_direct
    result = self.engine.clone(
        prompt_wav_path=prompt_audio_path,
    ...<5 lines>...
        progress_bar=progress_bar
    )
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\step_audio_editx\step_audio_editx_impl\tts.py", line 220, in clone
    self.preprocess_prompt_wav(prompt_wav_path)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\step_audio_editx\step_audio_editx_impl\tts.py", line 519, in preprocess_prompt_wav
    vq0206_codes, vq02_codes_ori, vq06_codes_ori = self.audio_tokenizer.wav2token(prompt_wav, prompt_wav_sr)
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\step_audio_editx\step_audio_editx_impl\tokenizer.py", line 120, in wav2token
    vq02_ori = self.get_vq02_code(audio)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\step_audio_editx\step_audio_editx_impl\tokenizer.py", line 135, in get_vq02_code
    torchaudio.save(_tmp_wav, audio, 16000, format="wav")
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\utils\compatibility\pytorch_patches.py", line 93, in _patched_torchaudio_save
    return _original_torchaudio_save(uri, src, sample_rate, **kwargs)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\__init__.py", line 178, in save
    return save_with_torchcodec(
        uri,
    ...<8 lines>...
        compression=compression,
    )
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\_torchcodec.py", line 340, in save_with_torchcodec
    raise RuntimeError(f"Failed to save audio to {uri}: {e}") from e
RuntimeError: Failed to save audio to <_io.BytesIO object at 0x000001E6CD25ED90>: Couldn't allocate AVFormatContext. The destination file is <_io.BytesIO object at 0x000001E6CD25ED90>, check the desired extension? Invalid argument
Prompt executed in 0.33 seconds
```

**Comment by diodiogod** [comment]
The transformers empty audio is a bug that took me hours to figure out when I was first implementing step audio editx. It's a thing in the other comfyui node, but it has been fixed in my bundled code. I run this with Transformers 4.57.1 and it works normally now. Previously to the fix it did need transformers 4.53.3 but not anymore. [I even opened a PR](https://github.com/huggingface/transformers/pull/42612) on transformers before realizing this was a bug on the step audiox config file, not on transformers, and only needed me to change a single line in the bundled code.

There might be other bugs introduced by having both nodes in the same environment, as you guys have been reporting. I'll investigate this as soon as I ca.

**Comment by diodiogod** [comment]
> Thanks for the clarification!
> 
> I just wanted to add a short update from my side in case it helps others.
> 
> I’m currently running Transformers 4.57.3 together with TTS Audio Suite 4.15.7, and I was still getting empty audio files with Step Audio EditX on Arch Linux. The only fix that solved the issue for me was adjusting the model configuration.
> 
> Specifically, I edited:
> 
> ```
> ComfyUI/models/TTS/step_audio_editx/Step-Audio-EditX/config.json
> ```
> 
> and added the following line at the end of the config:
> 
> ```
> "tie_word_embeddings": false
> ```
> 
> After this change, audio generation works correctly and consistently for me, with no further modifications required.
> 
> Thank you very much for the help and the explanation. With this minimal config fix everything is now working as expected. I had already removed the official Step Audio EditX custom node yesterday and am now using only TTS Audio Suite, which works great.
> 
> Thanks again for the excellent work!

Exactly that is the correct fix, but since it's a fix on a downloadable file, it needs to be patched either by the user (not sustainable since most users won't know how to do it) or by the code at runtime... So my code was not patching it? hum... I'll need to investigate it further.

**Comment by jason-mightynice** [comment]
The transformers fixes are great and I have removed the other step-audiox node that was causing a conflict.

However, I am still having issue with Step AudioX nodes. Plugging in other engines like index tts works fine. 

See both errors below. I am windows, pytorch 2.9.1. and tried torchcodec 0.8.1 and 0.9.1

thank you.

When trying ⚙️ Step Audio EditX Engine into 🎨 Step Audio EditX - Audio Editor, the error is

```
!!! Exception during processing !!! 'StepAudioTTS' object has no attribute 'edit_single'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\execution.py", line 516, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\execution.py", line 330, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\execution.py", line 304, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\execution.py", line 292, in process_inputs
    result = f(**inputs)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx_special/step_audio_editx_audio_editor_node.py", line 582, in edit_audio
    current_tensor = step_audio_engine.edit_single(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\utils\models\comfyui_model_wrapper\base_wrapper.py", line 398, in __getattr__
    return getattr(self.model, name)
AttributeError: 'StepAudioTTS' object has no attribute 'edit_single'
```

And when trying ⚙️ Step Audio EditX Engine into 🎤 TTS Text, the error is

```
Clone failed: Failed to save audio to <_io.BytesIO object at 0x0000028BEFBC8090>: Couldn't allocate AVFormatContext. The destination file is <_io.BytesIO object at 0x0000028BEFBC8090>, check the desired extension? Invalid argument
❌ TTS Text generation failed: Failed to save audio to <_io.BytesIO object at 0x0000028BEFBC8090>: Couldn't allocate AVFormatContext. The destination file is <_io.BytesIO object at 0x0000028BEFBC8090>, check the desired extension? Invalid argument
Traceback (most recent call last):
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\_torchcodec.py", line 338, in save_with_torchcodec
    encoder.to_file(uri, bit_rate=bit_rate)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchcodec\encoders\_audio_encoder.py", line 69, in to_file
    _core.encode_audio_to_file(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        samples=self._samples,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        desired_sample_rate=sample_rate,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_ops.py", line 841, in __call__
    return self._op(*args, **kwargs)
           ~~~~~~~~^^^^^^^^^^^^^^^^^
RuntimeError: Couldn't allocate AVFormatContext. The destination file is <_io.BytesIO object at 0x0000028BEFBC8090>, check the desired extension? Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\unified/tts_text_node.py", line 864, in generate_speech
    audio_segments = tts_processor.process_text(
        text=text,
    ...<3 lines>...
        max_chars_per_chunk=max_chars_per_chunk if max_chars_per_chunk > 0 else 400
    )
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx\step_audio_editx_processor.py", line 126, in process_text
    return self._process_character_switching(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        segment_objects, voice_mapping, params,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        enable_chunking, max_chars_per_chunk
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx\step_audio_editx_processor.py", line 188, in _process_character_switching
    self._process_character_block(segment.character, segment.text.strip(), voice_mapping,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                segment_params, enable_chunking, max_chars, audio_segments)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx\step_audio_editx_processor.py", line 245, in _process_character_block
    self._process_single_text_segment(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        character, content, voice_mapping, params, audio_segments
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\nodes\step_audio_editx\step_audio_editx_processor.py", line 398, in _process_single_text_segment
    audio_tensor = self.adapter._generate_direct(clean_text, voice_ref, params, character)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\adapters\step_audio_editx_adapter.py", line 314, in _generate_direct
    result = self.engine.clone(
        prompt_wav_path=prompt_audio_path,
    ...<5 lines>...
        progress_bar=progress_bar
    )
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\step_audio_editx\step_audio_editx_impl\tts.py", line 220, in clone
    self.preprocess_prompt_wav(prompt_wav_path)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\step_audio_editx\step_audio_editx_impl\tts.py", line 519, in preprocess_prompt_wav
    vq0206_codes, vq02_codes_ori, vq06_codes_ori = self.audio_tokenizer.wav2token(prompt_wav, prompt_wav_sr)
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\step_audio_editx\step_audio_editx_impl\tokenizer.py", line 121, in wav2token
    vq02_ori = self.get_vq02_code(audio)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\engines\step_audio_editx\step_audio_editx_impl\tokenizer.py", line 136, in get_vq02_code
    torchaudio.save(_tmp_wav, audio, 16000, format="wav")
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\ComfyUI\custom_nodes\tts_audio_suite\utils\compatibility\pytorch_patches.py", line 93, in _patched_torchaudio_save
    return _original_torchaudio_save(uri, src, sample_rate, **kwargs)
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\__init__.py", line 178, in save
    return save_with_torchcodec(
        uri,
    ...<8 lines>...
        compression=compression,
    )
  File "D:\ComfyUI_windows_latest\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\_torchcodec.py", line 340, in save_with_torchcodec
    raise RuntimeError(f"Failed to save audio to {uri}: {e}") from e
RuntimeError: Failed to save audio to <_io.BytesIO object at 0x0000028BEFBC8090>: Couldn't allocate AVFormatContext. The destination file is <_io.BytesIO object at 0x0000028BEFBC8090>, check the desired extension? Invalid argument
Prompt executed in 8.74 seconds
```

**Comment by jason-mightynice** [comment]
Wow, that was fast! I tested and it all works great!! Amazing work! thank you
